
name: Download minio helm and Upload to Releases

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Helm Chart
        run: |
          # 拉取 chart
          helm pull oci://registry-1.docker.io/bitnamicharts/minio --version 17.0.21

      - name: Create Release and Upload Asset
        uses: ncipollo/release-action@v1
        with:
          tag: minio-helm-17.0.21
          name: minio helm 17.0.21
          allowUpdates: true
          body: |
            Bitnami package for Apache Kafka 
            
            **Load image:**
            ```bash
            helm repo add bitnami https://charts.bitnami.com/bitnami
            helm install my-minio bitnami/minio --version 17.0.21
            helm pull oci://registry-1.docker.io/bitnamicharts/minio --version 17.0.21
            ```
          artifacts: "minio-17.0.21.tgz"
          token: ${{ secrets.GITHUB_TOKEN }}
